name: CI Shellcheck

on:
  push:
    branches: [ "main" ]
  workflow_call:  # allows other workflows to call this
  workflow_dispatch:  # allows manual run from the Actions tab

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Shellcheck (act only)
        if: ${{ env.ACT }}
        run: sudo apt update && sudo apt install shellcheck

      - name: Run shellcheck on any *.sh file
        run: find . -name "*.sh" -not -path "./.git/*" -print0 | xargs -r -0 shellcheck
